### ISSUE TITLE
[Bug] Traceback (most recent call last)

### ISSUE THREAD

**Issue by ZouloveGhack** [Starry-Wind/StarRailAssistant#249]
### 问题描述

Honkai_Star_Rail.<module>:151 - 3.1 - Traceback (most recent call last):
  File "C:\Users\Z\Downloads\Honkai-Star-Rail-latest\Honkai_Star_Rail.py", line 139, in <module>
    main()
  File "C:\Users\Z\Downloads\Honkai-Star-Rail-latest\Honkai_Star_Rail.py", line 49, in main
    map_instance.auto_map(start)  # 读取配置
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Z\Downloads\Honkai-Star-Rail-latest\tools\map.py", line 79, in auto_map
    self.calculated.auto_map(map_, False)
  File "C:\Users\Z\Downloads\Honkai-Star-Rail-latest\tools\calculated.py", line 168, in auto_map
    self.mouse_move(value)
  File "C:\Users\Z\Downloads\Honkai-Star-Rail-latest\tools\calculated.py", line 185, in mouse_move
    dx = int(x * 1295 / real_width)
             ~~~~~~~~~^~~~~~~~~~~~
ZeroDivisionError: division by zero

### 预期行为

继续跑图打怪

### 实际行为

进行 calculated.auto_map:158 - 3.1 - 执行map_2-3_3文件:10/18 {'mouse_move': 1200} 后就出问题了

### 截图或录屏

![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/28489226/3c904a29-c7c2-447d-98ca-f366958bc582)


### 自动锄大地脚本版本

latest Pre-release

### 星穹铁道区服

国际服

### 日志

[日志文件.log](https://github.com/Starry-Wind/Honkai-Star-Rail/files/11524168/default.log)

**Comment by hanuxxx** [comment]
今天在2-3_3遇到同样的问题
```
19:35:27 - INFO	| map.auto_map:79 - 3.1 -  地图加载完毕，加载时间为 0 秒
19:35:29 - INFO	| calculated.auto_map:176 - 3.1 -  开始寻路
19:35:29 - INFO	| calculated.auto_map:178 - 3.1 -  执行map_2-3_3文件:1/18 {'w': 7.213360786437988}
19:35:37 - INFO	| calculated.auto_map:178 - 3.1 -  执行map_2-3_3文件:2/18 {'s': 0.6492950916290283}
19:35:37 - INFO	| calculated.auto_map:178 - 3.1 -  执行map_2-3_3文件:3/18 {'d': 1.7122056484222412}
19:35:39 - INFO	| calculated.auto_map:178 - 3.1 -  执行map_2-3_3文件:4/18 {'w': 5.096607208251953}
19:35:44 - INFO	| calculated.auto_map:178 - 3.1 -  执行map_2-3_3文件:5/18 {'a': 3.282719135284424}
19:35:47 - INFO	| calculated.auto_map:178 - 3.1 -  执行map_2-3_3文件:6/18 {'w': 0.652400068283081}
19:35:48 - INFO	| calculated.auto_map:178 - 3.1 -  执行map_2-3_3文件:7/18 {'a': 7.282719135284424}
19:35:55 - INFO	| calculated.auto_map:178 - 3.1 -  执行map_2-3_3文件:8/18 {'d': 0.6610024929046631}
19:35:56 - INFO	| calculated.auto_map:178 - 3.1 -  执行map_2-3_3文件:9/18 {'w': 6.009446859359741}
19:36:02 - INFO	| calculated.auto_map:178 - 3.1 -  执行map_2-3_3文件:10/18 {'mouse_move': 1200}
19:36:02 - ERROR	| Honkai_Star_Rail.<module>:151 - 3.1 -  Traceback (most recent call last):
  File "E:\Downloads\Compressed\SRA-1.2.1\Honkai_Star_Rail.py", line 139, in <module>
    main()
  File "E:\Downloads\Compressed\SRA-1.2.1\Honkai_Star_Rail.py", line 49, in main
    map_instance.auto_map(start)  # 读取配置
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Downloads\Compressed\SRA-1.2.1\utils\map.py", line 82, in auto_map
    self.calculated.auto_map(map_, False)
  File "E:\Downloads\Compressed\SRA-1.2.1\utils\calculated.py", line 188, in auto_map
    self.mouse_move(value)
  File "E:\Downloads\Compressed\SRA-1.2.1\utils\calculated.py", line 205, in mouse_move
    dx = int(x * 1295 / real_width)
             ~~~~~~~~~^~~~~~~~~~~~
ZeroDivisionError: division by zero
```
