### ISSUE TITLE
不明原因无法启动

### ISSUE THREAD

**Issue by esdrtf** [Starry-Wind/StarRailAssistant#270]
之前的版本都是可以用的，今天下载更新了新的包后出现这个情况：
正在自动更新地图档
? 请选择运行平台 PC
? 请选择操作 大世界
? 请选择起始星球： 空间站「黑塔」
Honkai_Star_Rail.<module>:180 - 1.5 - Traceback (most recent call last):
  File "C:\Users\19492\DOWNLO~1\STARRA~1.7_T\STARRA~1.7_T\Honkai_Star_Rail.py", line 166, in <module>
    main(0,platform)
  File "C:\Users\19492\DOWNLO~1\STARRA~1.7_T\STARRA~1.7_T\Honkai_Star_Rail.py", line 62, in main
    start, role_list = choose_map(map_instance, type, platform)
    ^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

**Comment by esdrtf** [comment]
已解决
