### ISSUE TITLE
[Bug] ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2'

### ISSUE THREAD

**Issue by Chanpoe** [Starry-Wind/StarRailAssistant#290]
## torchvision.models.mobilenetv2包导入异常，运行大世界或者模拟宇宙都是秒退出，貌似日志log什么都没有记录。
python版本：3.11.3
pytorch版本如下：
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/84487466/b0a4b779-c410-4a4e-ad50-792c3875405e)

### 预期行为

希望可以获得成功导入的包的版本信息

### 实际行为

网络上说可能是版本兼容问题，希望作者可以在`requiremes.txt`中给出具体包的版本信息。

### 截图或录屏

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/84487466/d8d3e280-9664-4ab7-8d73-ff44e3f91a63)
报错文本信息：
```
(starrail) E:\Desktop\StarRailAssistant-1.5.4>python Honkai_Star_Rail.py
Traceback (most recent call last):
  File "E:\Desktop\StarRailAssistant-1.5.4\Honkai_Star_Rail.py", line 13, in <module>
    from utils.calculated import calculated
  File "E:\Desktop\StarRailAssistant-1.5.4\utils\calculated.py", line 9, in <module>
    from cnocr import CnOcr
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\cnocr\__init__.py", line 21, in <module>
    from .cn_ocr import CnOcr, gen_model
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\cnocr\cn_ocr.py", line 31, in <module>
    from cnocr.models.ocr_model import OcrModel
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\cnocr\models\ocr_model.py", line 34, in <module>
    from .mobilenet import gen_mobilenet_v3
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\cnocr\models\mobilenet.py", line 25, in <module>
    from torchvision.models.mobilenetv2 import ConvBNActivation
ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2' (D:\ProgramData\anaconda3\envs\starrail\Lib\site-packages\torchvision\models\mobilenetv2.py)
```

### 自动锄大地脚本版本

20230525234131

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11567906/default.log)

**Comment by Leot-0** [comment]
请问楼主解决了吗

**Comment by Night-stars-1** [comment]
提供一下你的cnocr版本

**Comment by Guoyh1212** [comment]
同样的问题，CNOCR版本是2.1.0
![2BUDC2B7T}N9(5X I8 K EY](https://github.com/Starry-Wind/StarRailAssistant/assets/93355016/2199c1c0-9d8b-4c8d-8476-fa79d6f962ea)

**Comment by Night-stars-1** [comment]
> 同样的问题，CNOCR版本是2.1.0，torch版本是2.0.1 ![2BUDC2B7T}N9(5X I8 K EY](https://user-images.githubusercontent.com/93355016/241112734-2199c1c0-9d8b-4c8d-8476-fa79d6f962ea.jpg) ![9EY(}D(W291_7@)R3AKB~T7](https://user-images.githubusercontent.com/93355016/241112980-02322d47-4173-4417-9c6b-3c5c8986507a.jpg)

更新cnocr版本，改问题最新版已经修复
cnocr最新版为2.2.2.3

**Comment by Chanpoe** [comment]
运行成功了，但是还是提示有报错如下：
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/84487466/55d9e8d6-37c0-4902-8e09-cca6823d7c9f)

## 完整报错如下：
```
(starrail) E:\Desktop\StarRailAssistant-1.5.4>python Honkai_Star_Rail.py
? 请选择运行平台 PC
? 请选择操作 大世界
[WARNING 2023-05-26 13:20:31,296 _assert_and_prepare_model_files:124] can not find model file C:\Users\Chanpoe\AppData\Roaming\cnstd\1.2\ppocr\ch_PP-OCRv2_det_infer.onnx
Honkai_Star_Rail.<module>:190 - 20230526115739/20230525234131/20230525234131 - Traceback (most recent call last):
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\starrail\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\starrail\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "D:\ProgramData\anaconda3\envs\starrail\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\starrail\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\starrail\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "D:\ProgramData\anaconda3\envs\starrail\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Desktop\StarRailAssistant-1.5.4\Honkai_Star_Rail.py", line 176, in <module>
    main(0,platform)
  File "E:\Desktop\StarRailAssistant-1.5.4\Honkai_Star_Rail.py", line 61, in main
    map_instance = Map(platform, order)
                   ^^^^^^^^^^^^^^^^^^^^
  File "E:\Desktop\StarRailAssistant-1.5.4\utils\map.py", line 21, in __init__
    self.calculated = calculated(platform,order)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Desktop\StarRailAssistant-1.5.4\utils\calculated.py", line 40, in __init__
    self.ocr = CnOcr(det_model_name='ch_PP-OCRv2_det', rec_model_name='densenet_lite_114-fc')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\cnocr\cn_ocr.py", line 169, in __init__
    self.det_model = CnStd(
                     ^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\cnstd\cn_std.py", line 98, in __init__
    self.det_model = det_cls(
                     ^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\cnstd\ppocr\pp_detector.py", line 69, in __init__
    self._assert_and_prepare_model_files(model_fp, root)
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\cnstd\ppocr\pp_detector.py", line 132, in _assert_and_prepare_model_files
    get_model_file(url, self._model_dir)  # download the .zip file and unzip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\cnstd\utils\utils.py", line 227, in get_model_file
    download(url, path=zip_file_path, overwrite=True)
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\cnstd\utils\utils.py", line 170, in download
    r = requests.get(url, stream=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 723, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
           ^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chanpoe\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
```

**Comment by Night-stars-1** [comment]
> 包导入成功了，但是还是提示有报错如下： ![image](https://user-images.githubusercontent.com/84487466/241126055-55d9e8d6-37c0-4902-8e09-cca6823d7c9f.png)
> 。。。。
>
文件下载失败，请检查网络

**Comment by Chanpoe** [comment]
> > 包导入成功了，但是还是提示有报错如下： ![image](https://user-images.githubusercontent.com/84487466/241126055-55d9e8d6-37c0-4902-8e09-cca6823d7c9f.png)
> > 。。。。
> 
> 文件下载失败，请检查网络

解决了orz
