### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LamorakLi** [Starry-Wind/StarRailAssistant#306]
### 问题描述

Traceback (most recent call last):
  File "D:\StarRailAssistant-main\Honkai_Star_Rail.py", line 22, in <module>
    def choose_map(map_instance: map_word, type = 0, platform = "PC"):
                                 ^^^^^^^^
NameError: name 'map_word' is not defined

### 预期行为

报错

### 实际行为

Traceback (most recent call last):
  File "D:\StarRailAssistant-main\Honkai_Star_Rail.py", line 22, in <module>
    def choose_map(map_instance: map_word, type = 0, platform = "PC"):
                                 ^^^^^^^^
NameError: name 'map_word' is not defined

### 自动锄大地脚本版本

2.7

### 星穹铁道区服

国服

### 日志

(star) PS D:\StarRailAssistant-main> python .\Honkai_Star_Rail.py
Traceback (most recent call last):
  File "D:\StarRailAssistant-main\Honkai_Star_Rail.py", line 13, in <module>
    from utils.calculated import calculated
  File "D:\StarRailAssistant-main\utils\calculated.py", line 10, in <module>
    from cnocr import CnOcr
  File "D:\Program Files\anaconda\envs\star\Lib\site-packages\cnocr\__init__.py", line 21, in <module>
    from .cn_ocr import CnOcr, gen_model
  File "D:\Program Files\anaconda\envs\star\Lib\site-packages\cnocr\cn_ocr.py", line 31, in <module>
    from cnocr.models.ocr_model import OcrModel
  File "D:\Program Files\anaconda\envs\star\Lib\site-packages\cnocr\models\ocr_model.py", line 34, in <module>
    from .mobilenet import gen_mobilenet_v3
  File "D:\Program Files\anaconda\envs\star\Lib\site-packages\cnocr\models\mobilenet.py", line 25, in <module>
    from torchvision.models.mobilenetv2 import ConvBNActivation
ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2' (D:\Program Files\anaconda\envs\star\Lib\site-packages\torchvision\models\mobilenetv2.py)

Traceback (most recent call last):
  File "D:\StarRailAssistant-main\Honkai_Star_Rail.py", line 22, in <module>
    def choose_map(map_instance: map_word, type = 0, platform = "PC"):
                                 ^^^^^^^^
NameError: name 'map_word' is not defined

**Comment by Night-stars-1** [comment]
更新cnocr版本为2.2.2.3
