### ISSUE TITLE
[Bug] ERROR: Could not install packages due to an OSError: [WinError 206] 文件名或扩展名太长

### ISSUE THREAD

**Issue by a776058959** [Starry-Wind/StarRailAssistant#309]
### 问题描述

第一次运行pip install -r requirements.txt之后没报错，然后打开游戏 再打开Python Honkai_Star_Rail.py就提示如下
Traceback (most recent call last):
  File "C:\Users\*****\Desktop\BH3\StarRailAssistant-latest\Honkai_Star_Rail.py", line 4, in <module>
    from utils.log import log
  File "C:\Users\*****\Desktop\BH3\StarRailAssistant-latest\utils\log.py", line 13, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

Traceback (most recent call last):
  File "C:\Users\*****\Desktop\BH3\StarRailAssistant-latest\Honkai_Star_Rail.py", line 25, in <module>
    def choose_map(map_instance: map_word, type = 0, platform = "PC"):
                                 ^^^^^^^^
NameError: name 'map_word' is not defined

然后再pip install -r requirements.txt之后就提示如下
ERROR: Could not install packages due to an OSError: [WinError 206] 文件名或扩展名太长。: 'C:\\Users\\*****\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\onnx\\backend\\test\\data\\node\\test_layer_normalization_3d_axis_negative_1_epsilon_expanded_ver18\\test_data_set_0'

然后再Python Honkai_Star_Rail.py 就还是
Traceback (most recent call last):
  File "C:\Users\*****\Desktop\BH3\StarRailAssistant-latest\Honkai_Star_Rail.py", line 4, in <module>
    from utils.log import log
  File "C:\Users\*****\Desktop\BH3\StarRailAssistant-latest\utils\log.py", line 13, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

### 预期行为

这时候按照指南应该进游戏等待/输入地图编号了吧

### 实际行为

然后手动一个一个安装缺少的依赖，直到装到cnocr的时候 报错文件名或扩展名太长，之后换豆瓣源可以安装。

再之后运行Python Honkai_Star_Rail.py提示如下
Traceback (most recent call last):
  File "C:\Users\*****\Desktop\BH3\StarRailAssistant-latest\Honkai_Star_Rail.py", line 16, in <module>
    from utils.calculated import calculated
  File "C:\Users\*****\Desktop\BH3\StarRailAssistant-latest\utils\calculated.py", line 10, in <module>
    from cnocr import CnOcr
  File "C:\Users\*****\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cnocr\__init__.py", line 21, in <module>
    from .cn_ocr import CnOcr, gen_model
  File "C:\Users\*****\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cnocr\cn_ocr.py", line 31, in <module>
    from cnocr.models.ocr_model import OcrModel
  File "C:\Users\*****\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cnocr\models\ocr_model.py", line 34, in <module>
    from .mobilenet import gen_mobilenet_v3
  File "C:\Users\*****\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cnocr\models\mobilenet.py", line 25, in <module>
    from torchvision.models.mobilenetv2 import ConvBNActivation
ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2' (C:\Users\*****\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torchvision\models\mobilenetv2.py)

Traceback (most recent call last):
  File "C:\Users\*****\Desktop\BH3\StarRailAssistant-latest\Honkai_Star_Rail.py", line 25, in <module>
    def choose_map(map_instance: map_word, type = 0, platform = "PC"):
                                 ^^^^^^^^
NameError: name 'map_word' is not defined

### 自动锄大地脚本版本

1.5.5

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11581301/default.log)

**Comment by Night-stars-1** [comment]
1.cnocr更新到最新版
2.标题上几个中文大字已经说明了问题
