### ISSUE TITLE
[Bug] 脚本异常退出，发生于事件“识别到疑问或是警告,等待怪物开战”之后

### ISSUE THREAD

**Issue by wenbuer** [Starry-Wind/StarRailAssistant#314]
### 问题描述

脚本多次异常退出，发生于事件“识别到疑问或是警告,等待怪物开战”之后

日志行为：

15:33:23 - INFO	| calculated.fighting:339 - 20230527145152/20230527020715/20230527020715 -  识别到疑问或是警告,等待怪物开战
15:33:26 - ERROR	| Honkai_Star_Rail.<module>:222 - 20230527145152/20230527020715/20230527020715 -  Traceback (most recent call last):
  File "F:\game\StarRailAssistant-1.5.4\Honkai_Star_Rail.py", line 208, in <module>
    main(0,platform)
  File "F:\game\StarRailAssistant-1.5.4\Honkai_Star_Rail.py", line 78, in main
    map_instance.auto_map(start)  # 读取配置
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\game\StarRailAssistant-1.5.4\utils\map.py", line 121, in auto_map
    self.start_map(map, False)
  File "F:\game\StarRailAssistant-1.5.4\utils\map.py", line 67, in start_map
    self.calculated.fighting()
  File "F:\game\StarRailAssistant-1.5.4\utils\calculated.py", line 342, in fighting
    result = self.scan_screenshot(target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\game\StarRailAssistant-1.5.4\utils\calculated.py", line 230, in scan_screenshot
    result = cv.matchTemplate(screenshot, prepared, cv.TM_CCORR_NORMED)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

### 预期行为

脚本正常进行

### 实际行为

闪退中止

### 自动锄大地脚本版本

v1.5.5

### 星穹铁道区服

国服

### 日志

[日志文件-0527.log](https://github.com/Starry-Wind/StarRailAssistant/files/11582415/-0527.log)

**Comment by Starry-Wind** [comment]
更新最新版本，已修复
