### ISSUE TITLE
[Bug] KeyError: '收容舱段'

### ISSUE THREAD

**Issue by Agnes4m** [Starry-Wind/StarRailAssistant#315]
### 问题描述

启动脚本，选择地图界面失败中断
python 3.11.3
win 10
git clone下载main分支最新版本
pc端
全屏1920*1080

### 预期行为

正常选择第一个地图

### 实际行为

在选择地图界面卡主

### 截图或录屏

中断界面
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/70925546/586490d9-14f5-48d9-a2f1-107485e811e7)
![image](https://github.com/Starry-Wind/StarRailAssistant/assets/70925546/82c68f3c-0be2-4d18-8df2-e8840482c3a0)

### 自动锄大地脚本版本

1.5.5

### 星穹铁道区服

国服

### 日志

```
? 请选择运行平台 PC
? 请选择操作 大世界
? 请选择起始星球： 空间站「黑塔」
? 请选择起始地图： 收容舱段-1
Honkai_Star_Rail.main:70 - 20230528003411/20230527234756/20230527234756 - 脚本将自动切换至游戏窗口，请保持游戏窗口激活
get_width.get_width:52 - 20230528003411/20230527234756/20230527234756 - Real resolution: 1536 x 864 x 1.2
Honkai_Star_Rail.main:75 - 20230528003411/20230527234756/20230527234756 - 开始运行，请勿移动鼠标和键盘
Honkai_Star_Rail.main:76 - 20230528003411/20230527234756/20230527234756 - 若脚本运行无反应,请使用管理员权限运行
requests.webhook_and_log:80 - 20230528003411/20230527234756/20230527234756 - 开始收容舱段-1锄地
map.auto_map:109 - 20230528003411/20230527234756/20230527234756 - 该路线导航作者：Starry-Wind,小明
map.auto_map:110 - 20230528003411/20230527234756/20230527234756 - 感谢每一位无私奉献的作者
[WARNING 2023-05-28 00:54:35,804 _showwarnmsg:109] D:\python3.11\Lib\site-packages\torchvision\transforms\functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(

calculated.open_map:683 - 20230528003411/20230527234756/20230527234756 - 识别超时
calculated.ocr_click:191 - 20230528003411/20230527234756/20230527234756 - 识别超时
Honkai_Star_Rail.<module>:222 - 20230528003411/20230527234756/20230527234756 - Traceback (most recent call last):
  File "E:\text\github\auto\StarRailAssistant\Honkai_Star_Rail.py", line 208, in <module>
    main(0,platform)
  File "E:\text\github\auto\StarRailAssistant\Honkai_Star_Rail.py", line 78, in main
    map_instance.auto_map(start)  # 读取配置
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text\github\auto\StarRailAssistant\utils\map.py", line 120, in auto_map
    self.calculated.click_target(key, 0.98)
  File "E:\text\github\auto\StarRailAssistant\utils\calculated.py", line 316, in click_target
    pos = ocr_data[temp_ocr[temp_name]]
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: '收容舱段'
```

**Comment by Night-stars-1** [comment]
识别超时，重新运行即可
