### ISSUE TITLE
[Bug] 在跑图至残响回廊2-3_3时出现了除0错误

### ISSUE THREAD

**Issue by yxc0915** [Starry-Wind/StarRailAssistant#349]
### 问题描述

在跑图至残响回廊2-3_3时出现了除0错误

### 预期行为

正常运行

### 实际行为

程序计算错误，闪退

### 截图或录屏

闪退

### 自动锄大地脚本版本

1.5.5

### 星穹铁道区服

国服

### 日志

11:38:39 - INFO	| map.start_map:56 - 0/0/20230528163825 -  执行map_2-3_3文件:10/18 {'mouse_move': 1200}
11:38:39 - ERROR	| Honkai_Star_Rail.<module>:232 - 0/0/20230528163825 -  Traceback (most recent call last):
  File "Honkai_Star_Rail.py", line 216, in <module>
  File "Honkai_Star_Rail.py", line 83, in main
  File "utils\map.py", line 128, in auto_map
    self.start_map(map, False)
  File "utils\map.py", line 64, in start_map
    self.calculated.Mouse_move(value)
  File "utils\calculated.py", line 421, in Mouse_move
    dx = int(x * 1295 / real_width)
ZeroDivisionError: division by zero

**Comment by Night-stars-1** [comment]
已修复
