### ISSUE TITLE
[Bug] prompt_toolkit.output.win32.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?

### ISSUE THREAD

**Issue by gongfuture** [Starry-Wind/StarRailAssistant#373]
### 问题描述

打开时报错

### 预期行为

1

### 实际行为

Honkai_Star_Rail.<module>:258 - 20230529231352/20230528163825/20230528163825 - Traceback (most recent call last):
  File "D:\Projects\StarRailAssistant\Honkai_Star_Rail.py", line 223, in <module>
    platform = questionary.select(title, options).ask()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\questionary\prompts\select.py", line 173, in select
    layout = common.create_inquirer_layout(ic, get_prompt_tokens, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\questionary\prompts\common.py", line 489, in create_inquirer_layout
    ps = PromptSession(get_prompt_tokens, reserve_space_for_menu=0, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 477, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 728, in _create_application
    application: Application[_T] = Application(
                                   ^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\application\application.py", line 273, in __init__
    self.output = output or session.output
                            ^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\application\current.py", line 68, in output
    self._output = create_output()
                   ^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\output\defaults.py", line 87, in create_output
    return Win32Output(stdout, default_color_depth=color_depth_from_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\output\win32.py", line 116, in __init__
    info = self.get_win32_screen_buffer_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\output\win32.py", line 220, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.output.win32.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?

* server not running *

进程已结束,退出代码0

### 自动锄大地脚本版本

2.7_test

### 星穹铁道区服

国服

### 日志

13:18:01 - ERROR	| Honkai_Star_Rail.<module>:258 - 20230529231352/20230528163825/20230528163825 -  Traceback (most recent call last):
  File "D:\Projects\StarRailAssistant\Honkai_Star_Rail.py", line 223, in <module>
    platform = questionary.select(title, options).ask()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\questionary\prompts\select.py", line 173, in select
    layout = common.create_inquirer_layout(ic, get_prompt_tokens, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\questionary\prompts\common.py", line 489, in create_inquirer_layout
    ps = PromptSession(get_prompt_tokens, reserve_space_for_menu=0, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 477, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 728, in _create_application
    application: Application[_T] = Application(
                                   ^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\application\application.py", line 273, in __init__
    self.output = output or session.output
                            ^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\application\current.py", line 68, in output
    self._output = create_output()
                   ^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\output\defaults.py", line 87, in create_output
    return Win32Output(stdout, default_color_depth=color_depth_from_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\output\win32.py", line 116, in __init__
    info = self.get_win32_screen_buffer_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\gongf\anaconda3\envs\Honkai-Star-Rail\Lib\site-packages\prompt_toolkit\output\win32.py", line 220, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.output.win32.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.ex

**Comment by Night-stars-1** [comment]
你应该补充更多信息，依赖是否安装，执行什么文件的报错

**Comment by gongfuture** [comment]
我的问题，我将pycharm以管理员模式启动了，主程序就自动在控制台运行，但我没打开控制台模拟终端
