### ISSUE TITLE
[Bug] 報錯 name 'map_word' is not defined

### ISSUE THREAD

**Issue by xeivu** [Starry-Wind/StarRailAssistant#391]
### 问题描述

StarRailAssistant-1.5.7

cmd執行Honkai_Star_Rail時報錯

C:\Windows\System32>"C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\Honkai_Star_Rail.py"
Traceback (most recent call last):
  File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\Honkai_Star_Rail.py", line 15, in <module>
    from utils.simulated_universe import Simulated_Universe
  File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\utils\simulated_universe.py", line 25, in <module>
    from .calculated import *
  File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\utils\calculated.py", line 11, in <module>
    from cnocr import CnOcr
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\__init__.py", line 21, in <module>
    from .cn_ocr import CnOcr, gen_model
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\cn_ocr.py", line 31, in <module>    from cnocr.models.ocr_model import OcrModel
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\models\ocr_model.py", line 34, in <module>
    from .mobilenet import gen_mobilenet_v3
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\models\mobilenet.py", line 25, in <module>
    from torchvision.models.mobilenetv2 import ConvBNActivation
ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2' (C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\mobilenetv2.py)

Traceback (most recent call last):
  File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\Honkai_Star_Rail.py", line 27, in <module>
    def choose_map(map_instance: map_word, type = 0, platform = "PC"):
                                 ^^^^^^^^
NameError: name 'map_word' is not defined

C:\Windows\System32>

### 预期行为

0

### 实际行为

0

### 自动锄大地脚本版本

2.7_test

### 星穹铁道区服

国际服

### 日志

C:\Windows\System32>"C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\Honkai_Star_Rail.py"
Traceback (most recent call last):
  File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\Honkai_Star_Rail.py", line 15, in <module>
    from utils.simulated_universe import Simulated_Universe
  File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\utils\simulated_universe.py", line 25, in <module>
    from .calculated import *
  File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\utils\calculated.py", line 11, in <module>
    from cnocr import CnOcr
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\__init__.py", line 21, in <module>
    from .cn_ocr import CnOcr, gen_model
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\cn_ocr.py", line 31, in <module>    from cnocr.models.ocr_model import OcrModel
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\models\ocr_model.py", line 34, in <module>
    from .mobilenet import gen_mobilenet_v3
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\models\mobilenet.py", line 25, in <module>
    from torchvision.models.mobilenetv2 import ConvBNActivation
ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2' (C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\mobilenetv2.py)

Traceback (most recent call last):
  File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\Honkai_Star_Rail.py", line 27, in <module>
    def choose_map(map_instance: map_word, type = 0, platform = "PC"):
                                 ^^^^^^^^
NameError: name 'map_word' is not defined

C:\Windows\System32>

**Comment by yxc0915** [comment]
這個問題看起來似乎是你的操作錯誤造成的，請嘗試重新安裝依賴確保安裝的是最新版本。建議不要使用第三方的pypi。

> ### 问题描述
> StarRailAssistant-1.5.7
> 
> cmd執行Honkai_Star_Rail時報錯
> 
> C:\Windows\System32>"C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\Honkai_Star_Rail.py" Traceback (most recent call last): File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\Honkai_Star_Rail.py", line 15, in from utils.simulated_universe import Simulated_Universe File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\utils\simulated_universe.py", line 25, in from .calculated import * File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\utils\calculated.py", line 11, in from cnocr import CnOcr File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr__init__.py", line 21, in from .cn_ocr import CnOcr, gen_model File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\cn_ocr.py", line 31, in from cnocr.models.ocr_model import OcrModel File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\models\ocr_model.py", line 34, in from .mobilenet import gen_mobilenet_v3 File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\models\mobilenet.py", line 25, in from torchvision.models.mobilenetv2 import ConvBNActivation ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2' (C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\mobilenetv2.py)
> 
> Traceback (most recent call last): File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\Honkai_Star_Rail.py", line 27, in def choose_map(map_instance: map_word, type = 0, platform = "PC"): ^^^^^^^^ NameError: name 'map_word' is not defined
> 
> C:\Windows\System32>
> 
> ### 预期行为
> 0
> 
> ### 实际行为
> 0
> 
> ### 截图或录屏
> _No response_
> 
> ### 自动锄大地脚本版本
> 2.7_test
> 
> ### 星穹铁道区服
> 国际服
> 
> ### 日志
> C:\Windows\System32>"C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\Honkai_Star_Rail.py" Traceback (most recent call last): File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\Honkai_Star_Rail.py", line 15, in from utils.simulated_universe import Simulated_Universe File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\utils\simulated_universe.py", line 25, in from .calculated import * File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\utils\calculated.py", line 11, in from cnocr import CnOcr File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr__init__.py", line 21, in from .cn_ocr import CnOcr, gen_model File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\cn_ocr.py", line 31, in from cnocr.models.ocr_model import OcrModel File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\models\ocr_model.py", line 34, in from .mobilenet import gen_mobilenet_v3 File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\cnocr\models\mobilenet.py", line 25, in from torchvision.models.mobilenetv2 import ConvBNActivation ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2' (C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\mobilenetv2.py)
> 
> Traceback (most recent call last): File "C:\Users\XeIVU\Downloads\StarRailAssistant-1.5.7\Honkai_Star_Rail.py", line 27, in def choose_map(map_instance: map_word, type = 0, platform = "PC"): ^^^^^^^^ NameError: name 'map_word' is not defined
> 
> C:\Windows\System32>

**Comment by Night-stars-1** [comment]
更新cnocr為2.2.3
