### ISSUE TITLE
[Bug] 启动时报错

### ISSUE THREAD

**Issue by gxy12345** [Starry-Wind/StarRailAssistant#414]
### 问题描述

启动后，选择PC-大世界，然后报错退出

### 预期行为

正常启动

### 实际行为

报错退出

### 截图或录屏

![image](https://github.com/Starry-Wind/StarRailAssistant/assets/13727139/9df8672f-e019-4d3d-a9ea-bc9a4e3f75a5)

### 自动锄大地脚本版本

1.5.7

### 星穹铁道区服

国际服

### 日志

21:32:33 - ERROR	| Honkai_Star_Rail.<module>:264 - 20230604205135/20230603155439/20230603155439 -  Traceback (most recent call last):
  File "I:\StarRailAssistant\StarRailAssistant-1.5.7\StarRailAssistant-1.5.7\Honkai_Star_Rail.py", line 250, in <module>
    select()
  File "I:\StarRailAssistant\StarRailAssistant-1.5.7\StarRailAssistant-1.5.7\Honkai_Star_Rail.py", line 243, in select
    main(0, platform)
  File "I:\StarRailAssistant\StarRailAssistant-1.5.7\StarRailAssistant-1.5.7\Honkai_Star_Rail.py", line 70, in main
    map_instance = map_word(platform, order, adb_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\StarRailAssistant\StarRailAssistant-1.5.7\StarRailAssistant-1.5.7\utils\map.py", line 21, in __init__
    self.calculated = calculated(platform,order,adb_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\StarRailAssistant\StarRailAssistant-1.5.7\StarRailAssistant-1.5.7\utils\calculated.py", line 43, in __init__
    self.ocr = CnOcr(det_model_name='ch_PP-OCRv3_det', rec_model_name='densenet_lite_114-fc')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Guo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cnocr\cn_ocr.py", line 155, in __init__
    self.rec_model = rec_cls(
                     ^^^^^^^^
  File "C:\Users\Guo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cnocr\recognizer.py", line 117, in __init__
    self._assert_and_prepare_model_files(model_fp, root)
  File "C:\Users\Guo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cnocr\recognizer.py", line 168, in _assert_and_prepare_model_files
    get_model_file(
  File "C:\Users\Guo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cnocr\utils.py", line 243, in get_model_file
    with zipfile.ZipFile(zip_file_path) as zf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\zipfile.py", line 1301, in __init__
    self._RealGetContents()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\zipfile.py", line 1368, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by Night-stars-1** [comment]
https://sra.stysqy.top/guide/qa.html

**Comment by gxy12345** [comment]
缺少OCR模型，下载后解决
