### ISSUE TITLE
[Bug] 1.6.0打开地图后报错退出

### ISSUE THREAD

**Issue by hanuxxx** [Starry-Wind/StarRailAssistant#448]
### 问题描述

自动按m开地图后程序报错退出

config.json内容如下
```
{
  "real_width": 1920,
  "auto_battle_persistence": 1,
  "real_height": 1080,
  "github_proxy": "https://ghproxy.com/",
  "rawgithub_proxy": "https://ghproxy.com/",
  "webhook_url": "",
  "start": true,
  "temp_version": "20230610185404",
  "star_version": "20230611181439",
  "open_map": "m",
  "level": "INFO",
  "adb": "127.0.0.1:21503",
  "adb_path": "temp\\adb\\adb",
  "proxies": "",
  "language": "zh_CN",
  "map_version": "20230610185404",
  "scaling": 1.0,
  "borderless": false,
  "left_border": 8.0,
  "up_border": 31.0
}
```
version.json文件内容如下，不知道是啥版本号，一起附上来吧
```{"version": "20230611025334"}```

### 预期行为

继续运行

### 实际行为

程序报错后，退出

### 自动锄大地脚本版本

1.6.0

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

```
19:08:06 - DEBUG	| map.read_maps:100 - 20230611181439/20230610185404/20230610185404 -  ['map_1-1_1.json', 'map_1-2_1.json', 'map_1-2_2.json', 'map_1-2_3.json', 'map_1-2_4.json', 'map_1-3_1.json', 'map_1-3_2.json', 'map_1-3_3.json', 'map_1-3_4.json', 'map_2-1_1.json', 'map_2-1_2.json', 'map_2-2_1.json', 'map_2-2_2.json', 'map_2-3_1.json', 'map_2-3_2.json', 'map_2-3_3.json', 'map_2-3_4.json', 'map_2-3_5.json', 'map_2-4_1.json', 'map_2-4_2.json', 'map_2-5_1.json', 'map_2-5_2.json', 'map_2-5_3.json', 'map_2-5_4.json', 'map_2-6_1.json', 'map_2-6_2.json', 'map_2-7_1.json', 'map_2-7_2.json', 'map_2-7_3.json', 'map_3-1_1.json', 'map_3-1_2.json', 'map_3-1_3.json', 'map_3-1_4.json', 'map_3-2_1.json', 'map_3-2_2.json', 'map_3-2_3.json', 'map_3-2_4.json', 'map_3-2_5.json', 'map_3-3_1.json', 'map_3-3_2.json', 'map_3-3_3.json', 'map_3-3_4.json', 'map_3-4_1.json', 'map_3-4_2.json', 'map_3-4_3.json', 'map_3-4_4.json', 'map_3-4_5.json', 'map_3-4_6.json']
19:08:06 - DEBUG	| map.read_maps:101 - 20230611181439/20230610185404/20230610185404 -  {'1': {'1_1': '基座舱段-1', '2_1': '收容舱段-1', '2_2': '收容舱段-2', '2_3': '收容舱段-2', '2_4': '收容舱段-3', '3_1': '支援舱段-1', '3_2': '支援舱段-2', '3_3': '支援舱段-3', '3_4': '支援舱段-4'}, '2': {'1_1': '城郊雪原-1', '1_2': '城郊雪原-2', '2_1': '边缘道路-1', '2_2': '边缘道路-2', '3_1': '残响回廊-1', '3_2': '残响回廊-2', '3_3': '残响回廊-3', '3_4': '残响回廊-4', '3_5': '残响回廊-5', '4_1': '永冬岭-1', '4_2': '永冬岭-2', '5_1': '大矿区-1', '5_2': '大矿区-2', '5_3': '大矿区-3', '5_4': '大矿区-4', '6_1': '铆钉镇-1', '6_2': '铆钉镇-2', '7_1': '机器聚落-1', '7_2': '机器聚落-2', '7_3': '机器聚落-3'}, '3': {'1_1': '流云渡-1', '1_2': '流云渡-2', '1_3': '流云渡-3', '1_4': '流云渡-4', '2_1': '迥星港-1', '2_2': '迥星港-2', '2_3': '迥星港-3', '2_4': '迥星港-4', '2_5': '迥星港-5', '3_1': '太卜司-1', '3_2': '太卜司-2', '3_3': '太卜司-3', '3_4': '太卜司-4', '4_1': '工造司-1', '4_2': '工造司-2', '4_3': '工造司-3', '4_4': '工造司-4', '4_5': '工造司-5', '4_6': '工造司-6'}}
19:08:08 - INFO	| Honkai_Star_Rail.main:130 - 20230611181439/20230610185404/20230610185404 -  脚本将自动切换至游戏窗口，请保持游戏窗口激活
19:08:08 - INFO	| get_width.get_width:56 - 20230611181439/20230610185404/20230610185404 -  Real resolution: 1936 x 1119 x 1.0 x False
19:08:08 - INFO	| Honkai_Star_Rail.main:136 - 20230611181439/20230610185404/20230610185404 -  开始运行，请勿移动鼠标和键盘
19:08:08 - INFO	| Honkai_Star_Rail.main:137 - 20230611181439/20230610185404/20230610185404 -  若脚本运行无反应,请使用管理员权限运行
19:08:08 - INFO	| map.auto_map:105 - 20230611181439/20230610185404/20230610185404 -  (1920, 1080)
19:08:08 - INFO	| requests.webhook_and_log:99 - 20230611181439/20230610185404/20230610185404 -  开始[0;34;40m基座舱段-1[0m锄地
19:08:08 - INFO	| map.auto_map:120 - 20230611181439/20230610185404/20230610185404 -  该路线导航作者：[0;31;40mStarry-Wind,小明[0m
19:08:08 - INFO	| map.auto_map:121 - 20230611181439/20230610185404/20230610185404 -  感谢每一位无私奉献的作者
19:08:08 - DEBUG	| map.auto_map:124 - 20230611181439/20230610185404/20230610185404 -  map
19:08:11 - DEBUG	| calculated.part_ocr:652 - 20230611181439/20230610185404/20230610185404 -  {'导航': (757, 313), 'Y': (704, 332), '空间站': (774, 342)}
19:08:11 - INFO	| calculated.open_map:802 - 20230611181439/20230610185404/20230610185404 -  进入地图
19:08:11 - ERROR	| Honkai_Star_Rail.<module>:363 - 20230611181439/20230610185404/20230610185404 -  Traceback (most recent call last):
  File "E:\Downloads\Compressed\StarRailAssistant-1.6.0\Honkai_Star_Rail.py", line 348, in <module>
    select()
  File "E:\Downloads\Compressed\StarRailAssistant-1.6.0\Honkai_Star_Rail.py", line 339, in select
    sra.main(0, platform)
  File "E:\Downloads\Compressed\StarRailAssistant-1.6.0\Honkai_Star_Rail.py", line 141, in main
    map_instance.auto_map(start)  # 读取配置
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Downloads\Compressed\StarRailAssistant-1.6.0\utils\map.py", line 129, in auto_map
    self.map_init()
  File "E:\Downloads\Compressed\StarRailAssistant-1.6.0\utils\map.py", line 37, in map_init
    shrink_result = self.calculated.scan_screenshot(target,(20,89,40,93))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Downloads\Compressed\StarRailAssistant-1.6.0\utils\calculated.py", line 240, in scan_screenshot
    result = cv.matchTemplate(screenshot, prepared, cv.TM_CCORR_NORMED)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'
```

**Comment by Night-stars-1** [comment]
图片文件忘记更新了，现在提交了，等一下更新图片即可
