### ISSUE TITLE
[Bug] 怪打完之后或者是进地图找不到怪识别超时会直接脚本崩溃

### ISSUE THREAD

**Issue by EnderOre** [Starry-Wind/StarRailAssistant#550]
### 问题描述

第一次进游戏选择的是基座舱段，然而基座舱段的怪已经先刷掉了，脚本识别不到怪然后就闪退了

选择其他的地图中如果位置没有怪也会闪退。

### 预期行为

怪物不见的时候会识别超时，识别超时后应该要前往下一个刷怪点或者是切换到下一个地图而不是闪退

### 实际行为

识别不到怪物就会闪退

### 截图或录屏

使用的是powershell
![3d8a390bf8d7e66d0e88424392c65bec](https://github.com/Starry-Wind/StarRailAssistant/assets/66881284/7960445d-fb03-4b84-8a4f-e74ba7bb0742)

### 自动锄大地脚本版本

1.6.4

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

日志文件较长，这里顺便提取一下报错的信息。
22:26:17 - INFO	| calculated.fighting:471 - 20230621204819/20230620003020/20230620003020 -  识别中
22:26:18 - INFO	| calculated.fighting:487 - 20230621204819/20230620003020/20230620003020 -  监控疑问或是警告
22:26:30 - INFO	| calculated.fighting:474 - 20230621204819/20230620003020/20230620003020 -  识别超时,此处可能无敌人
22:26:30 - ERROR	| Honkai_Star_Rail.<module>:335 - 20230621204819/20230620003020/20230620003020 -  Traceback (most recent call last):
  File "C:\Users\Telisa\Desktop\StarRailAssistant-1.6.4\Honkai_Star_Rail.py", line 328, in <module>
    select()
  File "C:\Users\Telisa\Desktop\StarRailAssistant-1.6.4\Honkai_Star_Rail.py", line 324, in select
    sra.main(option, platform)
  File "C:\Users\Telisa\Desktop\StarRailAssistant-1.6.4\Honkai_Star_Rail.py", line 283, in main
    map_instance.auto_map(start)  # 读取配置
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Telisa\Desktop\StarRailAssistant-1.6.4\utils\map.py", line 157, in auto_map
    start_map(self, start)
  File "C:\Users\Telisa\Desktop\StarRailAssistant-1.6.4\utils\map.py", line 154, in start_map
    self.start_map(map, map_name)
  File "C:\Users\Telisa\Desktop\StarRailAssistant-1.6.4\utils\map.py", line 77, in start_map
    if map_filename not in fight_data["data"]:
                           ~~~~~~~~~~^^^^^^^^

下面是日志文件 
[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/11819356/default.log)

**Comment by ShadowLastBox** [comment]
同遇到

**Comment by Night-stars-1** [comment]
已修复 #551
