### ISSUE TITLE
[Bug] 识别超时,此处可能无敌人 KeyError: 'data'

### ISSUE THREAD

**Issue by seriaati** [Starry-Wind/StarRailAssistant#563]
### 问题描述

執行 Honkai Star Rail.py
選擇 PC
選擇大世界
選擇黑塔空間站
腳本跑到一半自行退出了

### 预期行为

腳本正常繼續執行。

### 实际行为

腳本退出。

### 自动锄大地脚本版本

1.6.4

### 星穹铁道区服

国际服

### 运行的客户端

PC

### 日志

```
...
calculated.fighting:565 - 20230621223345/20230620003020/20230620003020 - 完成自动战斗
map.start_map:57 - 20230621223345/20230620003020/20230620003020 - 执行map_1-2_2文件:5/9 {'d': 2.0563018321990967}
map.start_map:57 - 20230621223345/20230620003020/20230620003020 - 执行map_1-2_2文件:6/9 {'d': 7.282793045043945}
map.start_map:57 - 20230621223345/20230620003020/20230620003020 - 执行map_1-2_2文件:7/9 {'w': 0.6022613048553467}
map.start_map:57 - 20230621223345/20230620003020/20230620003020 - 执行map_1-2_2文件:8/9 {'d': 0.26381516456604004}
map.start_map:57 - 20230621223345/20230620003020/20230620003020 - 执行map_1-2_2文件:9/9 {'fighting': 1}
calculated.fighting:472 - 20230621223345/20230620003020/20230620003020 - 识别中
calculated.fighting:488 - 20230621223345/20230620003020/20230620003020 - 监控疑问或是警告
calculated.fighting:475 - 20230621223345/20230620003020/20230620003020 - 识别超时,此处可能无敌人
Honkai_Star_Rail.<module>:335 - 20230621223345/20230620003020/20230620003020 - Traceback (most recent call last):
  File "C:\Users\seria\source\repos\StarRailAssistant-1.6.4\Honkai_Star_Rail.py", line 328, in <module>
    select()
  File "C:\Users\seria\source\repos\StarRailAssistant-1.6.4\Honkai_Star_Rail.py", line 324, in select
    sra.main(option, platform)
  File "C:\Users\seria\source\repos\StarRailAssistant-1.6.4\Honkai_Star_Rail.py", line 283, in main
    map_instance.auto_map(start)  # 读取配置
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\seria\source\repos\StarRailAssistant-1.6.4\utils\map.py", line 157, in auto_map
    start_map(self, start)
  File "C:\Users\seria\source\repos\StarRailAssistant-1.6.4\utils\map.py", line 154, in start_map
    self.start_map(map, map_name)
  File "C:\Users\seria\source\repos\StarRailAssistant-1.6.4\utils\map.py", line 77, in start_map
    if map_filename not in fight_data["data"]:
                           ~~~~~~~~~~^^^^^^^^
KeyError: 'data'

* server not running *
```

**Comment by cdcp998** [comment]
#562

**Comment by cdcp998** [comment]
#550 请更新下脚本.

**Comment by seriaati** [comment]
更新後不再出現此錯誤。
