### ISSUE TITLE
[Bug] 1.6.9更新资源出错

### ISSUE THREAD

**Issue by freefrank** [Starry-Wind/StarRailAssistant#650]
### 问题描述

这个版本更新资源时出错，详情见下。

另外，更新资源时会检测游戏是否运行，不记得之前版本是否也是这样。

### 预期行为

正确更新资源

### 实际行为

脚本报错，The system cannot find the path specified.

### 自动锄大地脚本版本

1.6.9

### 星穹铁道区服

国际服

### 运行的客户端

PC

### 日志

`Honkai_Star_Rail.<module>:332 - 20230716193844/20230715230112/20230715230112 - Traceback (most recent call last):
  File "C:\Users\service1\Desktop\StarRailAssistant\Honkai_Star_Rail.py", line 325, in <module>
    select() if not serial_map else sra.main(start=serial_map)
    ^^^^^^^^
  File "C:\Users\service1\Desktop\StarRailAssistant\Honkai_Star_Rail.py", line 320, in select
    sra.main(option)
  File "C:\Users\service1\Desktop\StarRailAssistant\Honkai_Star_Rail.py", line 291, in main
    self.option_dict[option]()
    ~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: '更新资源(脚本)'

The system cannot find the path specified.`

**Comment by freefrank** [comment]
回滚到1.6.8 可以正常运行。

**Comment by Night-stars-1** [comment]
#652 已修复
