### ISSUE TITLE
之前还好好的更新之后报错了

### ISSUE THREAD

**Issue by xcdlh** [Starry-Wind/StarRailAssistant#657]
### 问题描述

希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 地图加载完毕，加载时间为 0.0009906291961669922 秒
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 开始寻路
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 执行map_1-1_1文件:1/2 {'s': 3}
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 执行map_1-1_1文件:2/2 {'fighting': 1}
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 跳过开启自动战斗（沿用设置）
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 完成自动战斗
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 开始收容舱段-1锄地
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 该路线导航作者：Starry-Wind,小明
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 感谢每一位无私奉献的作者
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 进入地图
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - map_1-2
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 选择地图
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - map_1-2_point_1
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9956735372543335
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - transfer
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - Traceback (most recent call last):
  File "D:\StarRailAssistant-1.6.6\Honkai_Star_Rail.py", line 325, in <module>
    select() if not serial_map else sra.main(start=serial_map)
    ^^^^^^^^
  File "D:\StarRailAssistant-1.6.6\Honkai_Star_Rail.py", line 320, in select
    sra.main(option)
  File "D:\StarRailAssistant-1.6.6\Honkai_Star_Rail.py", line 272, in main
    map_instance.auto_map(start)  # 读取配置
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StarRailAssistant-1.6.6\utils\map.py", line 167, in auto_map
    start_map(self, start)
  File "D:\StarRailAssistant-1.6.6\utils\map.py", line 160, in start_map
    count = self.calculated.wait_join()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StarRailAssistant-1.6.6\utils\calculated.py", line 866, in wait_join
    if endtime > join_time:
       ^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'float' and 'dict'

### 预期行为

之前正常刷图

### 实际行为

报错了

### 自动锄大地脚本版本

1.6.9

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

星穹铁道小助手为开源项目，完全免费
如果你是购买的那么你被骗了
开源仓库地址: https://github.com/Starry-Wind/StarRailAssistant
? 请选择运行项目 大世界
? 请选择起始星球： 空间站「黑塔」
? 请选择起始地图： 基座舱段-1
Honkai_Star_Rail.main:262 - 20230718202750/20230715230112/20230715230112 - 脚本将自动切换至游戏窗口，请保持游戏窗口激活
get_width.get_width:54 - 20230718202750/20230715230112/20230715230112 - Real resolution: 1920 x 1080 x 1.0 x True
Honkai_Star_Rail.main:268 - 20230718202750/20230715230112/20230715230112 - 开始运行，请勿移动鼠标和键盘
Honkai_Star_Rail.main:269 - 20230718202750/20230715230112/20230715230112 - 若脚本运行无反应,请使用管理员权限运行
map.auto_map:99 - 20230718202750/20230715230112/20230715230112 - (1920, 1080)
[WARNING 2023-07-19 01:42:16,473 _showwarnmsg:109] C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\transforms\functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(

map.auto_map:103 - 20230718202750/20230715230112/20230715230112 - dict_keys(['希儿', '瓦尔特', '罗刹', '娜塔莎'])
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 开始基座舱段-1锄地
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 该路线导航作者：Starry-Wind,小明
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 感谢每一位无私奉献的作者
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 进入地图
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - map_1
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 选择地图
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - map_1_point
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9665840268135071
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9665840268135071
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9665806889533997
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9665787816047668
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9665787816047668
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9665787816047668
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9665787816047668
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.966589629650116
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9666520953178406
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.8897043466567993
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.8897043466567993
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 传送识别超时
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - transfer
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 识别超时
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 使用图片识别兜底
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - transfer
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9323540925979614
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.93233722448349
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9323543310165405
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9323667287826538
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.932363748550415
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9323553442955017
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9323628544807434
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9323977828025818
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9324003458023071
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.932395339012146
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9323585033416748
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9323604702949524
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.932390034198761
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9323931336402893
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9323634505271912
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 传送识别超时
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 已进入地图
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 地图加载完毕，加载时间为 0.0009906291961669922 秒
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 开始寻路
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 执行map_1-1_1文件:1/2 {'s': 3}
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 执行map_1-1_1文件:2/2 {'fighting': 1}
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 跳过开启自动战斗（沿用设置）
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 完成自动战斗
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 开始收容舱段-1锄地
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 该路线导航作者：Starry-Wind,小明
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 感谢每一位无私奉献的作者
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 进入地图
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - map_1-2
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 选择地图
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - map_1-2_point_1
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - 0.9956735372543335
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - transfer
希儿-瓦尔特-罗刹-娜塔莎 - 20230718202750/20230715230112/20230715230112 - Traceback (most recent call last):
  File "D:\StarRailAssistant-1.6.6\Honkai_Star_Rail.py", line 325, in <module>
    select() if not serial_map else sra.main(start=serial_map)
    ^^^^^^^^
  File "D:\StarRailAssistant-1.6.6\Honkai_Star_Rail.py", line 320, in select
    sra.main(option)
  File "D:\StarRailAssistant-1.6.6\Honkai_Star_Rail.py", line 272, in main
    map_instance.auto_map(start)  # 读取配置
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StarRailAssistant-1.6.6\utils\map.py", line 167, in auto_map
    start_map(self, start)
  File "D:\StarRailAssistant-1.6.6\utils\map.py", line 160, in start_map
    count = self.calculated.wait_join()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StarRailAssistant-1.6.6\utils\calculated.py", line 866, in wait_join
    if endtime > join_time:
       ^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'float' and 'dict'

**Comment by Night-stars-1** [comment]
把config里的join_time后面的东西改成数字
