### ISSUE TITLE
[Bug] ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by Shuntw6096** [Starry-Wind/StarRailAssistant#661]
### 问题描述

安裝StarRailAssistant 1.7

虛擬環境安裝完, 第一次運行 ```python .\Honkai_Star_Rail.py```, 出現錯誤。

有使用pip.ini設置global.index-url='https://mirrors.aliyun.com/pypi/simple'

### 预期行为

可以更新所有資源

### 实际行为

Traceback (most recent call last):
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\Honkai_Star_Rail.py", line 26, in <module>
    from utils.simulated_universe import Simulated_Universe
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\simulated_universe.py", line 28, in <module>
    from .requests import webhook_and_log
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\requests.py", line 21, in <module>
    proxies=sra_config_obj.proxies
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\config.py", line 291, in __getattribute__
    load_config_data(SRAData)
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\config.py", line 199, in load_config_data
    modify_json_file(CONFIG_FILE_NAME, lack_method, getattr(cls, lack_method))
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\config.py", line 63, in modify_json_file
    data, file_path = read_json_file(filename, path=True)
    ^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)

### 截图或录屏

Traceback (most recent call last):
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\Honkai_Star_Rail.py", line 26, in <module>
    from utils.simulated_universe import Simulated_Universe
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\simulated_universe.py", line 28, in <module>
    from .requests import webhook_and_log
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\requests.py", line 21, in <module>
    proxies=sra_config_obj.proxies
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\config.py", line 291, in __getattribute__
    load_config_data(SRAData)
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\config.py", line 199, in load_config_data
    modify_json_file(CONFIG_FILE_NAME, lack_method, getattr(cls, lack_method))
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\config.py", line 63, in modify_json_file
    data, file_path = read_json_file(filename, path=True)
    ^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)

### 自动锄大地脚本版本

v1.7.0

### 星穹铁道区服

国际服

### 运行的客户端

PC

### 日志

```
PS C:\Users\Clay\Desktop> python -m virtualenv star_rail
created virtual environment CPython3.11.4.final.0-64 in 930ms
  creator Venv(dest=C:\Users\Clay\Desktop\star_rail, clear=False, no_vcs_ignore=False, global=False, describe=CPython3Windows)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\Clay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv)
    added seed packages: pip==23.1.2, setuptools==68.0.0, wheel==0.40.0
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator



PS C:\Users\Clay\Desktop> .\star_rail\Scripts\activate
(star_rail) PS C:\Users\Clay\Desktop> cd .\star_rail\
(star_rail) PS C:\Users\Clay\Desktop\star_rail> cd .\StarRailAssistant-1.7.0\
(star_rail) PS C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0> pip config list
global.index-url='https://mirrors.aliyun.com/pypi/simple'




(star_rail) PS C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0> pip install -r requirements.txt
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Processing c:\users\clay\desktop\star_rail\starrailassistant-1.7.0\whl\polygon3-3.0.9-cp311-cp311-win_amd64.whl (from -r requirements.txt (line 9))
Processing c:\users\clay\desktop\star_rail\starrailassistant-1.7.0\whl\httpx_socks-0.7.7-py3-none-any.whl (from -r requirements.txt (line 26))
Collecting orjson (from -r requirements.txt (line 1))
  Downloading https://mirrors.aliyun.com/pypi/packages/f3/9e/1c647a12385befc803dad28be37f8625f4f244fc18a19038f1bbd889dd1b/orjson-3.9.2-cp311-none-win_amd64.whl (195 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.7/195.7 kB 320.8 kB/s eta 0:00:00
...
[notice] A new release of pip is available: 23.1.2 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip


(star_rail) PS C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0> python.exe -m pip install --upgrade pip
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: pip in c:\users\clay\desktop\star_rail\lib\site-packages (23.1.2)
Collecting pip
  Downloading https://mirrors.aliyun.com/pypi/packages/02/65/f15431ddee78562355ccb39097bf9160a1689f2db40dc418754be98806a1/pip-23.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 845.9 kB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
Successfully installed pip-23.2



(star_rail) PS C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0> python .\Honkai_Star_Rail.py
Traceback (most recent call last):
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\Honkai_Star_Rail.py", line 26, in <module>
    from utils.simulated_universe import Simulated_Universe
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\simulated_universe.py", line 28, in <module>
    from .requests import webhook_and_log
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\requests.py", line 21, in <module>
    proxies=sra_config_obj.proxies
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\config.py", line 291, in __getattribute__
    load_config_data(SRAData)
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\config.py", line 199, in load_config_data
    modify_json_file(CONFIG_FILE_NAME, lack_method, getattr(cls, lack_method))
  File "C:\Users\Clay\Desktop\star_rail\StarRailAssistant-1.7.0\utils\config.py", line 63, in modify_json_file
    data, file_path = read_json_file(filename, path=True)
    ^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by Shuntw6096** [comment]
從1.6.5更新到1.7.0發生無法更新的錯誤後，直接把之前的虛擬環境刪掉重新安裝1.7.0發生這個錯誤。

**Comment by Shuntw6096** [comment]
感覺還需要創建這份文件[config.json](https://github.com/Starry-Wind/StarRailAssistant#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E), 就可以進入程序了。

**Comment by Night-stars-1** [comment]
修了

**Comment by Shuntw6096** [comment]
@Night-stars-1 問個問題, 腳本怎麼錄製?
