### ISSUE TITLE
[Bug] 运行途中产生错误 cannot import name '_pyautogui_win' from partially initialized module 'pyautogui'

### ISSUE THREAD

**Issue by Aimerrhythm** [Starry-Wind/StarRailAssistant#706]
### 问题描述

运行报错，执行pip install pyautogui后还是产生这个问题
```
23:39:07 - ERROR	| Honkai_Star_Rail.<module>:355 - v1.7.3/20230830203446/20230830203446 -  Traceback (most recent call last):
  File "E:\StarRailTool\Auto_Star_Rail-1.7.3\Honkai_Star_Rail.py", line 348, in <module>
    select() if not serial_map else sra.main(start=serial_map)
    ^^^^^^^^
  File "E:\StarRailTool\Auto_Star_Rail-1.7.3\Honkai_Star_Rail.py", line 346, in select
    sra.main(option)
  File "E:\StarRailTool\Auto_Star_Rail-1.7.3\Honkai_Star_Rail.py", line 302, in main
    map_instance.auto_map(start)  # 读取配置
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StarRailTool\Auto_Star_Rail-1.7.3\utils\map.py", line 195, in auto_map
    start_map(self, start, True)
  File "E:\StarRailTool\Auto_Star_Rail-1.7.3\utils\map.py", line 182, in start_map
    self.calculated.click_target(key, 0.98, map=planet_number)
  File "E:\StarRailTool\Auto_Star_Rail-1.7.3\utils\calculated.py", line 379, in click_target
    import pyautogui
  File "D:\Anaconda3\envs\python3.11\Lib\site-packages\pyautogui\__init__.py", line 546, in <module>
    from . import _pyautogui_win as platformModule
ImportError: cannot import name '_pyautogui_win' from partially initialized module 'pyautogui' (most likely due to a circular import) (D:\Anaconda3\envs\python3.11\Lib\site-packages\pyautogui\__init__.py)
```

### 预期行为

已安装了pyautogui模块，不应该报错

### 实际行为

一般是在地图界面产生的错误

### 自动锄大地脚本版本

1.7.3

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/12706817/default.log)
[日志文件.log](https://github.com/Starry-Wind/StarRailAssistant/files/12706818/default.log)

**Comment by Night-stars-1** [comment]
你环境的问题，该程序仅import pyautogui

**Comment by Aimerrhythm** [comment]
我把calculate.py中的
`import pyautogui`
改为
`import sys
	    if "pyautogui" not in sys.modules:
                        import pyautogui`
就可以正常运行了
